spring:
    profiles:
        active: dev
        include: swagger
    devtools:
        restart:
            enabled: true
    jackson:
        serialization.indent_output: true
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:mem:recruting;DB_CLOSE_DELAY=-1
        username: recruting
        password: recruting
    h2:
        console:
            enabled: false
    jpa:
        database: H2
        show-sql: true
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
server:
    port: 8080
